version: '3.8'
services:
  mysql:
    container_name: auth_iitu_mysql_container
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_iitu_mysql_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          memory: "512M"

volumes:
  mysql_data:
